### ISSUE TITLE
ImportError: cannot import name 'Search' from 'googlesearch' (unknown location)

### ISSUE THREAD

**Issue by NicolasMICAUX** [Animenosekai/googlesearch#1]
The pypi version of the lib gives this error :
```
    from googlesearch import Search
ImportError: cannot import name 'Search' from 'googlesearch' (unknown location)
```

**Comment by Animenosekai** [comment]
Hmmm this shouldn't happen...

Try to use the CLI to check if it's really an import error.

If it's an import error try uninstalling and reinstalling the module.
